import type { NextPage } from "next";
import Head from "next/head";
import { AppLayout } from "@layouts/app";

const Home: NextPage = () => {
  return (
    <AppLayout>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>

      <span style={{ fontWeight: 700 }}>Hello</span>
      <span style={{ fontWeight: 700 }}>What are your plans for today?</span>
    </AppLayout>
  );
};

export default Home;
